[env]
EMMAKEN_CFLAGS = "-s ERROR_ON_UNDEFINED_SYMBOLS=0 -sEXTRA_EXPORTED_RUNTIME_METHODS=[ccall,cwrap] -s ASSERTIONS=1 -s SAFE_HEAP=1 -s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$readAsmConstArgs"
EMCC_DEBUG = "1"

[tasks.build]
clear = true
command = "cargo"
args = ["web", "build", "--use-system-emscripten"]

[tasks.test]
clear = true
dependencies = ['build']
command = "cargo"
args = ["web", "test", "--nodejs", "--use-system-emscripten", "--", "--nocapture"]
